[package]
name = "help-zet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.1"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
terminal_size = "0.2.5"
