[package]
name = "zet"
version = "0.1.1"
authors = ["Yarrow Angelweed <yarrow.angelweed@gmail.com>"]
description = "zet finds the union, intersection, set difference, etc of files considered as sets of lines"
documentation = "https://github.com/yarrow/zet"
homepage = "https://github.com/yarrow/zet"
repository = "https://github.com/yarrow/zet"
readme = "README.md"
keywords = ["set", "operation", "union", "uniq", "intersection"]
categories = ["command-line-utilities", "text-processing"]
license = "MIT OR Apache-2.0"
edition = '2018'

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
structopt = {version = "0.2.10", features=["wrap_help"]}
structopt-derive = "0.2.10"
clap = "2.32.0"
memchr = "2.0.1"
indexmap = "1.0.1"

[dev-dependencies]
assert_cmd = "0.10.1"
assert_fs = "0.2"
predicates = "0.5"
tempfile = "3.0.2"
itertools = "0.7.8"
